language: generic 
sudo: required
services:
  - docker
before_install:
    - docker build -t amitdocker/docker-react2 -f Dockerfile.dev .
script:
    - docker run -e CI=true amitdocker/docker-react2 npm run test


